package Aeroclub.app;

import Aeroclub.app.data.dataMember;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author logan.josse
 */
public class menuAeroclub extends javax.swing.JFrame {

    /**
     * Creates new form menuGestion
     */
    public menuAeroclub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headjPanel = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        backToMenujButton = new javax.swing.JButton();
        mainjLayeredPane = new javax.swing.JLayeredPane();
        separatorjPanel = new javax.swing.JPanel();
        menujPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        getMembresjButton = new javax.swing.JButton();
        membresjPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        addMemberjButton = new javax.swing.JButton();
        deleteMember = new javax.swing.JButton();
        membresjScrollPane = new javax.swing.JScrollPane();
        membresjTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aeroclub - Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headjPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        headjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlejLabel.setText("Aeroclub");
        headjPanel.add(titlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 35, 200, 40));

        backToMenujButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backToMenujButton.setText("<");
        backToMenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenujButtonActionPerformed(evt);
            }
        });
        headjPanel.add(backToMenujButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        getContentPane().add(headjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 110));

        separatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainjLayeredPane.add(separatorjPanel);
        separatorjPanel.setBounds(0, 0, 1440, 1);

        menujPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Vols");
        menujPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 400, 100));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Cotisations");
        menujPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 400, 100));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Abonnements");
        menujPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 400, 100));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Avions");
        menujPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 400, 100));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Instructeurs");
        menujPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 400, 100));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Catégories");
        menujPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 400, 100));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Plannings des vols");
        menujPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 400, 100));

        getMembresjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getMembresjButton.setText("Membres");
        getMembresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMembresjButtonActionPerformed(evt);
            }
        });
        menujPanel.add(getMembresjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 400, 100));

        mainjLayeredPane.add(menujPanel);
        menujPanel.setBounds(0, 0, 1440, 700);

        membresjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Modifier");
        membresjPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 250, 30));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Afficher");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        membresjPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 30));

        addMemberjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addMemberjButton.setText("Ajouter");
        addMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberjButtonActionPerformed(evt);
            }
        });
        membresjPanel.add(addMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 250, 30));

        deleteMember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteMember.setText("Supprimer");
        deleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemberActionPerformed(evt);
            }
        });
        membresjPanel.add(deleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 250, 30));

        membresjTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        membresjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "num_membre", "login", "password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        membresjScrollPane.setViewportView(membresjTable);
        if (membresjTable.getColumnModel().getColumnCount() > 0) {
            membresjTable.getColumnModel().getColumn(0).setResizable(false);
            membresjTable.getColumnModel().getColumn(1).setResizable(false);
            membresjTable.getColumnModel().getColumn(2).setResizable(false);
        }

        membresjPanel.add(membresjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1440, 650));

        mainjLayeredPane.add(membresjPanel);
        membresjPanel.setBounds(0, 0, 1440, 700);

        getContentPane().add(mainjLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1440, 700));
        switchPanels(menujPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenujButtonActionPerformed
        switchPanels(menujPanel);
    }//GEN-LAST:event_backToMenujButtonActionPerformed

    private void addMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberjButtonActionPerformed
        new addMemberModal().setVisible(true);
    }//GEN-LAST:event_addMemberjButtonActionPerformed

    private void getMembresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMembresjButtonActionPerformed
        switchPanels(membresjPanel);
        getMembersTable();
    }//GEN-LAST:event_getMembresjButtonActionPerformed

    private void deleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemberActionPerformed
        deleteMember();
    }//GEN-LAST:event_deleteMemberActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        getMember();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAeroclub().setVisible(true);
            }
        });
        
    }
    
    public void switchPanels(JPanel panel) {
        
        mainjLayeredPane.removeAll();
        mainjLayeredPane.add(separatorjPanel);
        if(panel == menujPanel) {
            backToMenujButton.setVisible(false);
        }else{
            backToMenujButton.setVisible(true);
        }
        mainjLayeredPane.add(panel);
        mainjLayeredPane.repaint();
        mainjLayeredPane.revalidate();
        
    }
    
    public void getMember() {
        
        int selectedRow = membresjTable.getSelectedRow();
        
        if(selectedRow != -1) {
            
            String num_membre = String.valueOf(membresjTable.getValueAt(selectedRow, 0));

            dataMember member = new dataMember();
            member.getMember(num_membre);

            new showMemberModal(member.num_membre).setVisible(true);
        
        }
        
    }
    
    public void addMember(String num_membre, String login, String password) {
        
        //new dataMember().addMember(num_membrejTextField.getText(), loginjTextField.getText(), passwordjPasswordField.getText());
        
        getMembersTable();
        
    }
    
    public void deleteMember() {
        
        int selectedRow = membresjTable.getSelectedRow();
        
        String num_membre = String.valueOf(membresjTable.getValueAt(selectedRow, 0));
        
        new dataMember().deleteMember(num_membre);
        
        getMembersTable();
        
    }
    
    public void getMembersTable() {
        
        Connection connection = null;
        DefaultTableModel tbmodel = (DefaultTableModel) membresjTable.getModel();
        tbmodel.setRowCount(0);
        
        try {
            
            database db = new database();
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://"+db.host+"/"+db.database, db.username, db.password);
            
            PreparedStatement ps = connection.prepareStatement("SELECT * FROM membres ASC;");
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                String num_membre = rs.getString("num_membre");
                String login = rs.getString("login");
                String password = rs.getString("password");

                String data[] = {num_membre, login, password};
                tbmodel.addRow(data);
            }
            
        } catch(ClassNotFoundException | SQLException e) {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemberjButton;
    private javax.swing.JButton backToMenujButton;
    private javax.swing.JButton deleteMember;
    private javax.swing.JButton getMembresjButton;
    private javax.swing.JPanel headjPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLayeredPane mainjLayeredPane;
    private javax.swing.JPanel membresjPanel;
    private javax.swing.JScrollPane membresjScrollPane;
    private javax.swing.JTable membresjTable;
    private javax.swing.JPanel menujPanel;
    private javax.swing.JPanel separatorjPanel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
