package Aeroclub.app;

import Aeroclub.app.data.database;
import Aeroclub.app.data.dataMember;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class menuAeroclub extends javax.swing.JFrame {

    /**
     * Creates new form menuGestion
     */
    public menuAeroclub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMemberjDialog = new javax.swing.JDialog();
        addMemberHeadjPanel = new javax.swing.JPanel();
        addMemberTitlejLabel = new javax.swing.JLabel();
        addMemberSeparatorjPanel = new javax.swing.JPanel();
        addMemberMainjPanel = new javax.swing.JPanel();
        addMemberjButton = new javax.swing.JButton();
        addMember_loginjLabel = new javax.swing.JLabel();
        addMember_num_membrejTextField = new javax.swing.JTextField();
        addMember_passwordjLabel = new javax.swing.JLabel();
        addMember_num_membrejLabel = new javax.swing.JLabel();
        addMember_loginjTextField = new javax.swing.JTextField();
        addMember_passwordjPasswordField = new javax.swing.JPasswordField();
        showMemberjDialog = new javax.swing.JDialog();
        showMemberHeadjPanel = new javax.swing.JPanel();
        showMemberTitlejLabel = new javax.swing.JLabel();
        showMemberSeparatorjPanel = new javax.swing.JPanel();
        showMemberMainjPanel = new javax.swing.JPanel();
        showMember_num_membrejLabel = new javax.swing.JLabel();
        showMember_loginjLabel = new javax.swing.JLabel();
        showMember_passwordjLabel = new javax.swing.JLabel();
        showMember_num_membreDatajLabel = new javax.swing.JLabel();
        showMember_loginDatajLabel = new javax.swing.JLabel();
        showMember_passwordDatajLabel = new javax.swing.JLabel();
        modifyMemberjDialog = new javax.swing.JDialog();
        modifyMemberHeadjPanel = new javax.swing.JPanel();
        modifyMemberTitlejLabel = new javax.swing.JLabel();
        modifyMemberSeparatorjPanel = new javax.swing.JPanel();
        modifyMemberMainjPanel = new javax.swing.JPanel();
        modifyMemberjButton = new javax.swing.JButton();
        modifyMember_loginjLabel = new javax.swing.JLabel();
        modifyMember_num_membrejTextField = new javax.swing.JTextField();
        modifyMember_passwordjLabel = new javax.swing.JLabel();
        modifyMember_num_membrejLabel = new javax.swing.JLabel();
        modifyMember_loginjTextField = new javax.swing.JTextField();
        modifyMember_passwordjPasswordField = new javax.swing.JPasswordField();
        deleteMemberjDialog = new javax.swing.JDialog();
        deleteMemberHeadjPanel = new javax.swing.JPanel();
        deleteMemberTitlejLabel = new javax.swing.JLabel();
        deleteMemberSeparatorjPanel = new javax.swing.JPanel();
        deleteMemberMainjPanel = new javax.swing.JPanel();
        deleteMember_canceljButton = new javax.swing.JButton();
        deleteMember_submitjButton = new javax.swing.JButton();
        headjPanel = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        backToMenujButton = new javax.swing.JButton();
        mainjLayeredPane = new javax.swing.JLayeredPane();
        separatorjPanel = new javax.swing.JPanel();
        menujPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        getMembresjButton = new javax.swing.JButton();
        membresjPanel = new javax.swing.JPanel();
        openModifyMemberjButton = new javax.swing.JButton();
        openShowMemberjButton = new javax.swing.JButton();
        openAddMemberjButton = new javax.swing.JButton();
        openDeleteMember = new javax.swing.JButton();
        membresjScrollPane = new javax.swing.JScrollPane();
        membresjTable = new javax.swing.JTable();

        addMemberjDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMemberjDialog.setAlwaysOnTop(true);
        addMemberjDialog.setBounds(new java.awt.Rectangle(0, 0, 400, 600));
        addMemberjDialog.setIconImage(null);
        addMemberjDialog.setLocationByPlatform(true);
        addMemberjDialog.setMinimumSize(new java.awt.Dimension(400, 600));
        addMemberjDialog.setResizable(false);
        addMemberjDialog.setSize(new java.awt.Dimension(400, 600));
        addMemberjDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMemberHeadjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMemberTitlejLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        addMemberTitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMemberTitlejLabel.setText("Ajout d'un membre");
        addMemberHeadjPanel.add(addMemberTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        addMemberjDialog.getContentPane().add(addMemberHeadjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        addMemberSeparatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        addMemberjDialog.getContentPane().add(addMemberSeparatorjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 1));

        addMemberMainjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addMemberjButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMemberjButton.setText("Ajouter");
        addMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberjButtonActionPerformed(evt);
            }
        });
        addMemberMainjPanel.add(addMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 100, 30));

        addMember_loginjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMember_loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addMember_loginjLabel.setText("login");
        addMemberMainjPanel.add(addMember_loginjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        addMember_num_membrejTextField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMemberMainjPanel.add(addMember_num_membrejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 20));

        addMember_passwordjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMember_passwordjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addMember_passwordjLabel.setText("password");
        addMemberMainjPanel.add(addMember_passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));

        addMember_num_membrejLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMember_num_membrejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addMember_num_membrejLabel.setText("num_membre");
        addMemberMainjPanel.add(addMember_num_membrejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 20));

        addMember_loginjTextField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMemberMainjPanel.add(addMember_loginjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 20));

        addMember_passwordjPasswordField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        addMemberMainjPanel.add(addMember_passwordjPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 20));

        addMemberjDialog.getContentPane().add(addMemberMainjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 550));

        addMemberjDialog.setLocationRelativeTo(null);

        showMemberjDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        showMemberjDialog.setAlwaysOnTop(true);
        showMemberjDialog.setBounds(new java.awt.Rectangle(0, 0, 400, 600));
        showMemberjDialog.setLocationByPlatform(true);
        showMemberjDialog.setMinimumSize(new java.awt.Dimension(400, 600));
        showMemberjDialog.setResizable(false);
        showMemberjDialog.setSize(new java.awt.Dimension(400, 600));
        showMemberjDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showMemberHeadjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showMemberTitlejLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        showMemberTitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showMemberTitlejLabel.setText("Détails du membre");
        showMemberHeadjPanel.add(showMemberTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        showMemberjDialog.getContentPane().add(showMemberHeadjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        showMemberSeparatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        showMemberjDialog.getContentPane().add(showMemberSeparatorjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 1));

        showMemberMainjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showMember_num_membrejLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_num_membrejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        showMember_num_membrejLabel.setText("num_membre :");
        showMember_num_membrejLabel.setToolTipText("");
        showMemberMainjPanel.add(showMember_num_membrejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 20));

        showMember_loginjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        showMember_loginjLabel.setText("login :");
        showMember_loginjLabel.setToolTipText("");
        showMemberMainjPanel.add(showMember_loginjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        showMember_passwordjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_passwordjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        showMember_passwordjLabel.setText("password :");
        showMember_passwordjLabel.setToolTipText("");
        showMemberMainjPanel.add(showMember_passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));

        showMember_num_membreDatajLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_num_membreDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showMemberMainjPanel.add(showMember_num_membreDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 20));

        showMember_loginDatajLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_loginDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showMemberMainjPanel.add(showMember_loginDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 20));

        showMember_passwordDatajLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        showMember_passwordDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showMemberMainjPanel.add(showMember_passwordDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 20));

        showMemberjDialog.getContentPane().add(showMemberMainjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 550));

        showMemberjDialog.setLocationRelativeTo(null);

        modifyMemberjDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modifyMemberjDialog.setAlwaysOnTop(true);
        modifyMemberjDialog.setBounds(new java.awt.Rectangle(0, 0, 400, 600));
        modifyMemberjDialog.setLocationByPlatform(true);
        modifyMemberjDialog.setMinimumSize(new java.awt.Dimension(400, 600));
        modifyMemberjDialog.setPreferredSize(new java.awt.Dimension(400, 600));
        modifyMemberjDialog.setResizable(false);
        modifyMemberjDialog.setSize(new java.awt.Dimension(400, 600));
        modifyMemberjDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyMemberHeadjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyMemberTitlejLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        modifyMemberTitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modifyMemberTitlejLabel.setText("Modification du membre");
        modifyMemberHeadjPanel.add(modifyMemberTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        modifyMemberjDialog.getContentPane().add(modifyMemberHeadjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        modifyMemberSeparatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        modifyMemberjDialog.getContentPane().add(modifyMemberSeparatorjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 1));

        modifyMemberMainjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyMemberjButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMemberjButton.setText("Modifier");
        modifyMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyMemberjButtonActionPerformed(evt);
            }
        });
        modifyMemberMainjPanel.add(modifyMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 100, 30));

        modifyMember_loginjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMember_loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        modifyMember_loginjLabel.setText("login");
        modifyMemberMainjPanel.add(modifyMember_loginjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        modifyMember_num_membrejTextField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMemberMainjPanel.add(modifyMember_num_membrejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 20));

        modifyMember_passwordjLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMember_passwordjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        modifyMember_passwordjLabel.setText("password");
        modifyMemberMainjPanel.add(modifyMember_passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));

        modifyMember_num_membrejLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMember_num_membrejLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        modifyMember_num_membrejLabel.setText("num_membre");
        modifyMemberMainjPanel.add(modifyMember_num_membrejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 20));

        modifyMember_loginjTextField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMemberMainjPanel.add(modifyMember_loginjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 20));

        modifyMember_passwordjPasswordField.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        modifyMemberMainjPanel.add(modifyMember_passwordjPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 20));

        modifyMemberjDialog.getContentPane().add(modifyMemberMainjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 550));

        modifyMemberjDialog.setLocationRelativeTo(null);

        deleteMemberjDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        deleteMemberjDialog.setAlwaysOnTop(true);
        deleteMemberjDialog.setBounds(new java.awt.Rectangle(0, 0, 400, 180));
        deleteMemberjDialog.setMinimumSize(new java.awt.Dimension(400, 180));
        deleteMemberjDialog.setPreferredSize(new java.awt.Dimension(400, 180));
        deleteMemberjDialog.setResizable(false);
        deleteMemberjDialog.setSize(new java.awt.Dimension(400, 180));
        deleteMemberjDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteMemberHeadjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteMemberTitlejLabel.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        deleteMemberTitlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteMemberTitlejLabel.setText("Suppression du membre");
        deleteMemberHeadjPanel.add(deleteMemberTitlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        deleteMemberjDialog.getContentPane().add(deleteMemberHeadjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        deleteMemberSeparatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        deleteMemberjDialog.getContentPane().add(deleteMemberSeparatorjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 1));

        deleteMemberMainjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteMember_canceljButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        deleteMember_canceljButton.setText("Annuler");
        deleteMember_canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMember_canceljButtonActionPerformed(evt);
            }
        });
        deleteMemberMainjPanel.add(deleteMember_canceljButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 50, 100, 30));

        deleteMember_submitjButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        deleteMember_submitjButton.setText("Supprimer");
        deleteMember_submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMember_submitjButtonActionPerformed(evt);
            }
        });
        deleteMemberMainjPanel.add(deleteMember_submitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, 100, 30));

        deleteMemberjDialog.getContentPane().add(deleteMemberMainjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 130));

        deleteMemberjDialog.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aeroclub - Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headjPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        headjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlejLabel.setText("Aeroclub");
        headjPanel.add(titlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 35, 200, 40));

        backToMenujButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backToMenujButton.setText("<");
        backToMenujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenujButtonActionPerformed(evt);
            }
        });
        headjPanel.add(backToMenujButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 50));

        getContentPane().add(headjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 110));

        separatorjPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainjLayeredPane.add(separatorjPanel);
        separatorjPanel.setBounds(0, 0, 1440, 1);

        menujPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Vols");
        menujPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 400, 100));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Cotisations");
        menujPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 400, 100));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Abonnements");
        menujPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 400, 100));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Avions");
        menujPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 400, 100));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Instructeurs");
        menujPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 400, 100));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Catégories");
        menujPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, 400, 100));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Plannings des vols");
        menujPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, 400, 100));

        getMembresjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getMembresjButton.setText("Membres");
        getMembresjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMembresjButtonActionPerformed(evt);
            }
        });
        menujPanel.add(getMembresjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 400, 100));

        mainjLayeredPane.add(menujPanel);
        menujPanel.setBounds(0, 0, 1440, 700);

        membresjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openModifyMemberjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openModifyMemberjButton.setText("Modifier");
        openModifyMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openModifyMemberjButtonActionPerformed(evt);
            }
        });
        membresjPanel.add(openModifyMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 250, 30));

        openShowMemberjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openShowMemberjButton.setText("Afficher");
        openShowMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openShowMemberjButtonActionPerformed(evt);
            }
        });
        membresjPanel.add(openShowMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 30));

        openAddMemberjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openAddMemberjButton.setText("Ajouter");
        openAddMemberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAddMemberjButtonActionPerformed(evt);
            }
        });
        membresjPanel.add(openAddMemberjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 250, 30));

        openDeleteMember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        openDeleteMember.setText("Supprimer");
        openDeleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDeleteMemberActionPerformed(evt);
            }
        });
        membresjPanel.add(openDeleteMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 250, 30));

        membresjTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        membresjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "num_membre", "login", "password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        membresjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        membresjTable.getTableHeader().setReorderingAllowed(false);
        membresjScrollPane.setViewportView(membresjTable);
        if (membresjTable.getColumnModel().getColumnCount() > 0) {
            membresjTable.getColumnModel().getColumn(0).setResizable(false);
            membresjTable.getColumnModel().getColumn(1).setResizable(false);
            membresjTable.getColumnModel().getColumn(2).setResizable(false);
        }

        membresjPanel.add(membresjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1410, 630));

        mainjLayeredPane.add(membresjPanel);
        membresjPanel.setBounds(0, 0, 1420, 680);

        getContentPane().add(mainjLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1440, 700));
        switchPanels(menujPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenujButtonActionPerformed
        switchPanels(menujPanel);
    }//GEN-LAST:event_backToMenujButtonActionPerformed

    private void openAddMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAddMemberjButtonActionPerformed
        addMember_num_membrejTextField.setText("");
        addMember_loginjTextField.setText("");
        addMember_passwordjPasswordField.setText("");
        addMemberjDialog.setVisible(true);
    }//GEN-LAST:event_openAddMemberjButtonActionPerformed

    private void getMembresjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMembresjButtonActionPerformed
        switchPanels(membresjPanel);
        getMembersTable();
    }//GEN-LAST:event_getMembresjButtonActionPerformed

    private void openDeleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDeleteMemberActionPerformed
        deleteMemberjDialog.setVisible(true);
    }//GEN-LAST:event_openDeleteMemberActionPerformed

    private void openShowMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openShowMemberjButtonActionPerformed
        getMember();
    }//GEN-LAST:event_openShowMemberjButtonActionPerformed

    private void openModifyMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openModifyMemberjButtonActionPerformed
        openModifyMember();
    }//GEN-LAST:event_openModifyMemberjButtonActionPerformed

    private void addMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberjButtonActionPerformed
        addMember();
    }//GEN-LAST:event_addMemberjButtonActionPerformed

    private void modifyMemberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyMemberjButtonActionPerformed
        modifyMember();
    }//GEN-LAST:event_modifyMemberjButtonActionPerformed

    private void deleteMember_canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMember_canceljButtonActionPerformed
        deleteMemberjDialog.dispose();
    }//GEN-LAST:event_deleteMember_canceljButtonActionPerformed

    private void deleteMember_submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMember_submitjButtonActionPerformed
        deleteMember();
    }//GEN-LAST:event_deleteMember_submitjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAeroclub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAeroclub().setVisible(true);
            }
        });
        
    }
    
    public void switchPanels(JPanel panel) {
        
        mainjLayeredPane.removeAll();
        mainjLayeredPane.add(separatorjPanel);
        if(panel == menujPanel) {
            backToMenujButton.setVisible(false);
        }else{
            backToMenujButton.setVisible(true);
        }
        mainjLayeredPane.add(panel);
        mainjLayeredPane.repaint();
        mainjLayeredPane.revalidate();
        
    }
    
    public void getMember() {
        
        int selectedRow = membresjTable.getSelectedRow();
        
        if(selectedRow != -1) {
            
            String num_membre = String.valueOf(membresjTable.getValueAt(selectedRow, 0));

            dataMember member = new dataMember();
            member.getMember(Integer.parseInt(num_membre));
            
            showMember_num_membreDatajLabel.setText(String.valueOf(member.num_membre));
            showMember_loginDatajLabel.setText(member.login);
            showMember_passwordDatajLabel.setText(member.password);

            showMemberjDialog.setVisible(true);
            
        
        }
        
    }
    
    public void addMember() {
        
        new dataMember().addMember(Integer.parseInt(addMember_num_membrejTextField.getText()), addMember_loginjTextField.getText(), addMember_passwordjPasswordField.getText());
        
        addMemberjDialog.dispose();
        
        getMembersTable();
        
    }
    
    public void openModifyMember() {
        
        int selectedRow = membresjTable.getSelectedRow();
        
        if(selectedRow != -1) {
            
            String num_membre = String.valueOf(membresjTable.getValueAt(selectedRow, 0));

            dataMember member = new dataMember();
            member.getMember(Integer.parseInt(num_membre));
            
            modifyMember_num_membrejTextField.setText(String.valueOf(member.num_membre));
            modifyMember_loginjTextField.setText(member.login);
            modifyMember_passwordjPasswordField.setText(member.password);

            modifyMemberjDialog.setVisible(true);
        
        }
        
    }
    
    public void modifyMember() {
        
        new dataMember().modifyMember(Integer.parseInt(modifyMember_num_membrejTextField.getText()), modifyMember_loginjTextField.getText(), modifyMember_passwordjPasswordField.getText());
        
        modifyMemberjDialog.dispose();
        
        getMembersTable();
        
    }
    
    public void deleteMember() {
        
        int selectedRow = membresjTable.getSelectedRow();
        
        int num_membre = Integer.parseInt((String) membresjTable.getValueAt(selectedRow, 0));
        
        new dataMember().deleteMember(num_membre);
        
        deleteMemberjDialog.dispose();
        
        getMembersTable();
        
    }
    
    public void getMembersTable() {
        
        Connection connection = null;
        DefaultTableModel tbmodel = (DefaultTableModel) membresjTable.getModel();
        tbmodel.setRowCount(0);
        
        try {
            
            database db = new database();
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://"+db.host+"/"+db.database, db.username, db.password);
            
            PreparedStatement ps = connection.prepareStatement("SELECT * FROM membres ORDER BY num_membre ASC;");
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()) {
                String num_membre = rs.getString("num_membre");
                String login = rs.getString("login");
                String password = rs.getString("password");

                String data[] = {num_membre, login, password};
                tbmodel.addRow(data);
            }
            
        } catch(ClassNotFoundException | SQLException e) {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMemberHeadjPanel;
    private javax.swing.JPanel addMemberMainjPanel;
    private javax.swing.JPanel addMemberSeparatorjPanel;
    private javax.swing.JLabel addMemberTitlejLabel;
    private javax.swing.JLabel addMember_loginjLabel;
    private javax.swing.JTextField addMember_loginjTextField;
    private javax.swing.JLabel addMember_num_membrejLabel;
    private javax.swing.JTextField addMember_num_membrejTextField;
    private javax.swing.JLabel addMember_passwordjLabel;
    private javax.swing.JPasswordField addMember_passwordjPasswordField;
    private javax.swing.JButton addMemberjButton;
    private javax.swing.JDialog addMemberjDialog;
    private javax.swing.JButton backToMenujButton;
    private javax.swing.JPanel deleteMemberHeadjPanel;
    private javax.swing.JPanel deleteMemberMainjPanel;
    private javax.swing.JPanel deleteMemberSeparatorjPanel;
    private javax.swing.JLabel deleteMemberTitlejLabel;
    private javax.swing.JButton deleteMember_canceljButton;
    private javax.swing.JButton deleteMember_submitjButton;
    private javax.swing.JDialog deleteMemberjDialog;
    private javax.swing.JButton getMembresjButton;
    private javax.swing.JPanel headjPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLayeredPane mainjLayeredPane;
    private javax.swing.JPanel membresjPanel;
    private javax.swing.JScrollPane membresjScrollPane;
    private javax.swing.JTable membresjTable;
    private javax.swing.JPanel menujPanel;
    private javax.swing.JPanel modifyMemberHeadjPanel;
    private javax.swing.JPanel modifyMemberMainjPanel;
    private javax.swing.JPanel modifyMemberSeparatorjPanel;
    private javax.swing.JLabel modifyMemberTitlejLabel;
    private javax.swing.JLabel modifyMember_loginjLabel;
    private javax.swing.JTextField modifyMember_loginjTextField;
    private javax.swing.JLabel modifyMember_num_membrejLabel;
    private javax.swing.JTextField modifyMember_num_membrejTextField;
    private javax.swing.JLabel modifyMember_passwordjLabel;
    private javax.swing.JPasswordField modifyMember_passwordjPasswordField;
    private javax.swing.JButton modifyMemberjButton;
    private javax.swing.JDialog modifyMemberjDialog;
    private javax.swing.JButton openAddMemberjButton;
    private javax.swing.JButton openDeleteMember;
    private javax.swing.JButton openModifyMemberjButton;
    private javax.swing.JButton openShowMemberjButton;
    private javax.swing.JPanel separatorjPanel;
    private javax.swing.JPanel showMemberHeadjPanel;
    private javax.swing.JPanel showMemberMainjPanel;
    private javax.swing.JPanel showMemberSeparatorjPanel;
    private javax.swing.JLabel showMemberTitlejLabel;
    private javax.swing.JLabel showMember_loginDatajLabel;
    private javax.swing.JLabel showMember_loginjLabel;
    private javax.swing.JLabel showMember_num_membreDatajLabel;
    private javax.swing.JLabel showMember_num_membrejLabel;
    private javax.swing.JLabel showMember_passwordDatajLabel;
    private javax.swing.JLabel showMember_passwordjLabel;
    private javax.swing.JDialog showMemberjDialog;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
