package Aeroclub.app;

import Aeroclub.app.data.dataMember;

/**
 *
 * @author zykow
 */
public class showMemberModal extends javax.swing.JFrame {
    /**
     * Creates new form addMemberModal
     */
    public showMemberModal(String num_membre) {
        initComponents();
        
        num_membreDatajLabel.setText(num_membre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headjPanel1 = new javax.swing.JPanel();
        titlejLabel1 = new javax.swing.JLabel();
        separatorjPanel1 = new javax.swing.JPanel();
        mainjPanel = new javax.swing.JPanel();
        num_membreDatajLabel = new javax.swing.JLabel();
        loginDatajLabel = new javax.swing.JLabel();
        passwordDatajLabel = new javax.swing.JLabel();
        num_membrejLabel1 = new javax.swing.JLabel();
        loginjLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headjPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        headjPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlejLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titlejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlejLabel1.setText("Ajout d'un membre");
        headjPanel1.add(titlejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        getContentPane().add(headjPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        separatorjPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(separatorjPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 1));

        mainjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num_membreDatajLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num_membreDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainjPanel.add(num_membreDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 20));

        loginDatajLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainjPanel.add(loginDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 20));

        passwordDatajLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordDatajLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainjPanel.add(passwordDatajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, 20));

        num_membrejLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num_membrejLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        num_membrejLabel1.setText("num_membre :");
        mainjPanel.add(num_membrejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 20));

        loginjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginjLabel.setText("login :");
        mainjPanel.add(loginjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 20));

        passwordjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordjLabel.setText("password :");
        mainjPanel.add(passwordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));

        getContentPane().add(mainjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showMemberModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showMemberModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showMemberModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showMemberModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showMemberModal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headjPanel1;
    private javax.swing.JLabel loginDatajLabel;
    private javax.swing.JLabel loginjLabel;
    private javax.swing.JPanel mainjPanel;
    private javax.swing.JLabel num_membreDatajLabel;
    private javax.swing.JLabel num_membrejLabel1;
    private javax.swing.JLabel passwordDatajLabel;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JPanel separatorjPanel1;
    private javax.swing.JLabel titlejLabel1;
    // End of variables declaration//GEN-END:variables
}
